package com.lagradost.cloudstream3

/**
 * Clean-room re-implementation of CloudStream3's `SearchResponse` sealed
 * hierarchy. Only mutable property setters used by the real plugin ecosystem
 * (observed via dex analysis of published `.cs3` files) are exposed. Plugins
 * call `set*` via synthetic accessors generated by Kotlin, so the fields must
 * be `var` to retain binary compatibility.
 */
abstract class SearchResponse {
    abstract val name: String
    abstract val url: String
    abstract val apiName: String
    abstract var type: TvType?
    abstract var posterUrl: String?
    abstract var posterHeaders: Map<String, String>?
    abstract var id: Int?
    abstract var quality: SearchQuality?
}

/** Matches CloudStream's public enum literals. */
enum class SearchQuality {
    P4k, P2160, P1440, P1080, P720, P480, P360, HD, SD, Cam, CamRip, HdCam,
    Telesync, WorkPrint, Telecine, HQ, HDTS, Unknown
}

data class MovieSearchResponse(
    override val name: String,
    override val url: String,
    override val apiName: String,
    override var type: TvType? = TvType.Movie,
    override var posterUrl: String? = null,
    override var posterHeaders: Map<String, String>? = null,
    override var id: Int? = null,
    override var quality: SearchQuality? = null,
    var year: Int? = null
) : SearchResponse()

data class TvSeriesSearchResponse(
    override val name: String,
    override val url: String,
    override val apiName: String,
    override var type: TvType? = TvType.TvSeries,
    override var posterUrl: String? = null,
    override var posterHeaders: Map<String, String>? = null,
    override var id: Int? = null,
    override var quality: SearchQuality? = null,
    var year: Int? = null,
    var episodes: Int? = null
) : SearchResponse()

data class AnimeSearchResponse(
    override val name: String,
    override val url: String,
    override val apiName: String,
    override var type: TvType? = TvType.Anime,
    override var posterUrl: String? = null,
    override var posterHeaders: Map<String, String>? = null,
    override var id: Int? = null,
    override var quality: SearchQuality? = null,
    var year: Int? = null,
    var dubStatus: EnumSet<DubStatus>? = null,
    var dubEpisodes: Int? = null,
    var subEpisodes: Int? = null,
    var otherName: String? = null
) : SearchResponse()

data class LiveSearchResponse(
    override val name: String,
    override val url: String,
    override val apiName: String,
    override var type: TvType? = TvType.Live,
    override var posterUrl: String? = null,
    override var posterHeaders: Map<String, String>? = null,
    override var id: Int? = null,
    override var quality: SearchQuality? = null,
    var lang: String? = null
) : SearchResponse()

data class TorrentSearchResponse(
    override val name: String,
    override val url: String,
    override val apiName: String,
    override var type: TvType? = TvType.Torrent,
    override var posterUrl: String? = null,
    override var posterHeaders: Map<String, String>? = null,
    override var id: Int? = null,
    override var quality: SearchQuality? = null
) : SearchResponse()

/** Minimal EnumSet shim — CloudStream defines its own. */
class EnumSet<T : Enum<T>> private constructor(
    private val set: MutableSet<T> = mutableSetOf()
) : Set<T> by set {
    fun add(element: T): Boolean = set.add(element)
    fun addAll(elements: Collection<T>): Boolean = set.addAll(elements)

    companion object {
        @JvmStatic fun <T : Enum<T>> noneOf(clazz: Class<T>): EnumSet<T> = EnumSet()
        @JvmStatic fun <T : Enum<T>> of(value: T): EnumSet<T> =
            EnumSet<T>().also { it.add(value) }
    }
}

enum class DubStatus {
    None,
    Dubbed,
    Subbed
}
