[build]
  publish = "."

[[redirects]]
  from = "/app"
  to = "https://web.arvio.tv"
  status = 302
  force = true

[[redirects]]
  from = "/app/*"
  to = "https://web.arvio.tv/:splat"
  status = 302
  force = true
